stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  BACKEND_IMAGE: "$CI_REGISTRY_IMAGE/backend"
  FRONTEND_IMAGE: "$CI_REGISTRY_IMAGE/frontend"

build_backend:
  stage: build
  image: docker:27
  services:
    - docker:dind
  script:
    - echo "Building backend docker images..."
    #- docker build -t "epi-devorapp-backend" ./backend
    #- docker tag epi-devorapp-backend:latest epi-devorapp-backend:$CI_COMMIT_SHORT_SHA
    #- echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    #- docker push $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main
    - tags

build_frontend:
  stage: build
  image: docker:27
  services:
    - docker:dind
  script:
    - echo "Building frontend docker image..."
    #- docker build -t "epi-devorapp-frontend" ./frontend
    #- docker tag epi-devorapp-frontend:latest epi-devorapp-frontend:$CI_COMMIT_SHORT_SHA
    #- echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    #- docker push $FRONTEND_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main
    - tags
